# Generated by Django 4.2.1 on 2023-05-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_bookcardsmodel_shop_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcardsmodel',
            old_name='shop_cost',
            new_name='book_cost',
        ),
    ]
