# Generated by Django 4.2.3 on 2023-07-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_bookcardsmodel_book_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcardsmodel',
            name='book_cost',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
