# Generated by Django 4.2.3 on 2023-07-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_bookcardsmodel_book_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
