# Generated by Django 4.2.3 on 2023-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_order_user_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcardsmodel',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
