# Generated by Django 4.2.6 on 2023-10-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_rename_phone_number_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcardsmodel',
            name='book_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bookcardsmodel',
            name='book_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
