# Generated by Django 4.2.6 on 2023-10-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_bookcardsmodel_book_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
